doctrine:
    dbal:
        driver: 'pdo_mysql'
        server_version: 'mariadb-10.11'
        charset: utf8mb4
        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        metadata_cache_driver:
            type: pool
            pool: cache.system
        query_cache_driver:
            type: pool
            pool: cache.system
        result_cache_driver:
            type: pool
            pool: cache.app
        mappings:
            App:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
