security:
    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        db_user_provider:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        health:
            pattern: ^/health$
            security: false
        main:
            lazy: true
            provider: db_user_provider
            http_basic: true

    access_control:
        - { path: ^/manage, roles: ROLE_ADMIN }
